"""add pitconfig

Revision ID: c22d2e32fe48
Revises: 
Create Date: 2026-03-27 17:12:17.606755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22d2e32fe48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pit_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('pit_token', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pit_config_id'), 'pit_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pit_config_id'), table_name='pit_config')
    op.drop_table('pit_config')
    # ### end Alembic commands ###
