"""add contact table and pit_config

Revision ID: e0e4fc6cad71
Revises: 
Create Date: 2026-03-29 22:30:47.562945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e4fc6cad71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pit_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('pit_token', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id')
    )
    op.create_index(op.f('ix_pit_config_id'), 'pit_config', ['id'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['pit_config.location_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    op.drop_index(op.f('ix_pit_config_id'), table_name='pit_config')
    op.drop_table('pit_config')
    # ### end Alembic commands ###
